### PR TITLE
Feature/346 remove hardcoded translations

### PR DESCRIPTION
**Pull request by marc89763**
Removed hardcoded translations. Not everything is translated yet. Also frontend tests need to be adapted. Assertions like `assert.ok(text.includes("Neue Skills"));` now fail, because "Neue Skills" was replaced by a variable in the template.

### CODE REVIEW

**Comment by Robin481** [comment]
Nice!
Let's plan a follow up task for the next Iteration and leave this Pull Request open so you can just keep on pushing onto this one.

**Comment by Robin481** [comment]
I created a follow-up task: https://github.com/puzzle/skills/issues/444

**Comment by marc89763** [comment]
All frontend tests pass again for
```
this.get("moment").setLocale("de");
this.get("intl").setLocale(["de"]);
```
in application.js.
There are still failing frontend tests for
```
this.get("moment").setLocale("en");
this.get("intl").setLocale(["en"]);
```
in application.js. But fewer tests fail than before and the 2 still failing tests are unrelated to my changes, they fail because of the different date format when moment is set to english.

**Review by Robin481 — APPROVED** [review]
Hey @marc89763
Nice work!
I've approved the PR already but please be so kind to add an Issue for your aforementioned issue concerning the English language settings.

**Pull request merged**
